spring:
  config:
    import: "classpath:env.properties"
  datasource:
    url: "jdbc:postgresql://localhost:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: validate # validate to let Flyway manage the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 60000 # 1 minute, for testing
      refresh-token:
        expiration: 180000 # 3 minutes, for testing
      cookie:
        jwt-cookie-name: ${JWT_COOKIE_NAME}
        jwt-refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME}
        max-age: ${JWT_COOKIE_MAX_AGE}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-doc
    enabled: true